// <auto-generated />
using System;
using Laboratoire2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laboratoire2.Migrations
{
    [DbContext(typeof(ContexteApplication))]
    [Migration("20230527013649_sprint1")]
    partial class sprint1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Laboratoire2.Models.Clients", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CommandeID")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CommandeID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Laboratoire2.Models.Commande", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaniersID")
                        .HasColumnType("int");

                    b.Property<int>("vetementID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PaniersID");

                    b.HasIndex("vetementID");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Laboratoire2.Models.Inventaire", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Inventaires");
                });

            modelBuilder.Entity("Laboratoire2.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("Restant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeID");

                    b.ToTable("LigneCommande");
                });

            modelBuilder.Entity("Laboratoire2.Models.LigneInventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventaireID")
                        .HasColumnType("int");

                    b.Property<int>("LigneCommandeId")
                        .HasColumnType("int");

                    b.Property<int>("VetementID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventaireID");

                    b.HasIndex("LigneCommandeId");

                    b.HasIndex("VetementID");

                    b.ToTable("LigneInventaire");
                });

            modelBuilder.Entity("Laboratoire2.Models.Paniers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("Laboratoire2.Models.Vetement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("InventaireID")
                        .HasColumnType("int");

                    b.Property<string>("NomVetement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyVetement")
                        .HasColumnType("int");

                    b.Property<int>("ResteVetement")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InventaireID");

                    b.ToTable("Vetements");
                });

            modelBuilder.Entity("Laboratoire2.Models.Clients", b =>
                {
                    b.HasOne("Laboratoire2.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Laboratoire2.Models.Commande", b =>
                {
                    b.HasOne("Laboratoire2.Models.Paniers", null)
                        .WithMany("commande")
                        .HasForeignKey("PaniersID");

                    b.HasOne("Laboratoire2.Models.Vetement", "vetement")
                        .WithMany()
                        .HasForeignKey("vetementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vetement");
                });

            modelBuilder.Entity("Laboratoire2.Models.LigneCommande", b =>
                {
                    b.HasOne("Laboratoire2.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Laboratoire2.Models.LigneInventaire", b =>
                {
                    b.HasOne("Laboratoire2.Models.Inventaire", "Inventaire")
                        .WithMany()
                        .HasForeignKey("InventaireID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratoire2.Models.LigneCommande", "LigneCommande")
                        .WithMany()
                        .HasForeignKey("LigneCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laboratoire2.Models.Vetement", "Vetement")
                        .WithMany()
                        .HasForeignKey("VetementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventaire");

                    b.Navigation("LigneCommande");

                    b.Navigation("Vetement");
                });

            modelBuilder.Entity("Laboratoire2.Models.Vetement", b =>
                {
                    b.HasOne("Laboratoire2.Models.Inventaire", null)
                        .WithMany("vetement")
                        .HasForeignKey("InventaireID");
                });

            modelBuilder.Entity("Laboratoire2.Models.Inventaire", b =>
                {
                    b.Navigation("vetement");
                });

            modelBuilder.Entity("Laboratoire2.Models.Paniers", b =>
                {
                    b.Navigation("commande");
                });
#pragma warning restore 612, 618
        }
    }
}
